version: '3'
services:
  

  db:
    image: postgres
    environment:
      POSTGRES_USER: 'sungano'
      POSTGRES_PASSWORD: '19981123'
      POSTGRES_DB: 'db'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - bridge-network


  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./ShadyStyle:/app
    depends_on:
      - db
    networks:
      - bridge-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge

volumes:
  db-data:
