version: '3.7'

services:
  shadystyle:
    volumes:
      - static:/app/staticfiles
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - static:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - shadystyle 

volumes:
  static: