# Generated by Django 4.2.5 on 2023-10-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sunglass',
            name='decription',
            field=models.TextField(default='this is a <django.db.models.fields.CharField>', max_length=200),
        ),
    ]
