# Generated by Django 4.2.5 on 2023-10-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_sunglass_decription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sunglass',
            name='decription',
            field=models.TextField(default='this is a <django.db.models.fields.CharField>', max_length=500),
        ),
    ]
