# Generated by Django 4.2.5 on 2023-10-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_sunglass_decription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sunglass',
            old_name='decription',
            new_name='description',
        ),
    ]
